function myspiderplot(P,clr)
% Initialize data points
% Spider plot
% D1 = [5 3 9 1 2];
% D2 = [5 8 7 2 9];
% D3 = [8 2 1 4 6];
% P = [D1; D2; D3];
p=[P];
spider_plot(p,'AxesLimits', [0, 0, 0; 0.8, 1, 1],...
   'AxesLabels', {'State',['Learned',sprintf('\n'), 'behavior'],['CS',sprintf('\n'), 'valance']},... 
   'LineWidth', [4],...
   'Color', clr,...
       'AxesLabelsOffset', 0.2,...
    'AxesDataOffset', 0.1,...
   'FillOption', 'on',...
   'AxesLabelsEdge', 'none',...
   'LineStyle','-',...
       'AxesFont', 'Times New Roman',...
    'LabelFont', 'Times New Roman',...
      'LabelFontSize', 12);
% spider_plot(P,...
%     'AxesLabels', {'State','CS valance', 'Learned behavior'},...
%     'AxesInterval', 4,...
%     'AxesPrecision', 0,...
%     'AxesDisplay', 'one',...
%     'AxesLimits', [0, 0, 0; 1, 1, 1],...
%     'FillOption', 'on',...
%     'FillTransparency', 0.2,...
%     'Color', clr,...
%     'LineStyle', {'-',},...
%     'LineWidth', [2],...
%     'LineTransparency', 1,...
%     'Marker', {'o'},...
%     'MarkerSize', [8],...
%     'MarkerTransparency', 1,...
%     'AxesFont', 'Times New Roman',...
%     'LabelFont', 'Times New Roman',...
%     'AxesFontSize', 12,...
%     'LabelFontSize', 14,...
%     'Direction', 'clockwise',...
%     'AxesDirection', {'normal', 'normal', 'normal'},...
%     'AxesScaling', 'linear',...
%     'AxesColor', [0.5, 0.5, 0.5],...
%     'AxesLabelsEdge', 'none',...
%     'AxesOffset', 1,...
%     'AxesZoom', 1,...
%     'AxesHorzAlign', 'quadrant',...
%     'AxesVertAlign', 'quadrant',...
%     'PlotVisible', 'on',...
%     'AxesTickLabels', 'data',...
%     'AxesInterpreter', 'tex',...
%     'BackgroundColor' , 'w',...
%     'MinorGrid', 'off',...
%     'MinorGridInterval', 2,...
%     'AxesZero', 'off',...
%     'AxesZeroColor', 'k',...
%     'AxesZeroWidth', 2,...
%     'AxesRadial', 'on',...
%     'AxesWeb', 'on',...
%     'AxesShaded', 'off',...
%     'AxesShadedLimits', [],...
%     'AxesShadedColor', 'g',...
%     'AxesShadedTransparency', 0.2,...
%     'AxesLabelsRotate', 'off');
end