function plot_sepplot(ind_frames,acti,str,frame,trial)

[~,~,sig]=sepplot_20181222(ind_frames,acti,str);hold on;
%US line
line([trial.hab(3)*frame.per_cycle+frame.us_start:frame.per_cycle:trial.acq(3)*frame.per_cycle;trial.hab(3)*frame.per_cycle+frame.us_start:frame.per_cycle:trial.acq(3)*frame.per_cycle]',...
    [min(sig(:)) max(sig(:))],'color','r','linestyle','--');hold on;
%CS bar
color=[0.5 0.5 0.5];
patch([[frame.cs_start+trial.spon_bef(3)*frame.per_cycle:frame.per_cycle:frame.per_cycle*trial.test(3)]'...
    [frame.cs_end+trial.spon_bef(3)*frame.per_cycle:frame.per_cycle:frame.per_cycle*trial.test(3)]'...
    [frame.cs_end+trial.spon_bef(3)*frame.per_cycle:frame.per_cycle:frame.per_cycle*trial.test(3)]'...
    [frame.cs_start+trial.spon_bef(3)*frame.per_cycle:frame.per_cycle:frame.per_cycle*trial.test(3)]']',...
    repmat([min(sig(:)) min(sig(:)) max(sig(:)) max(sig(:))],trial.test(3)-trial.hab(2)+1,1)',...
    color,'edgecolor',color,'facecolor',color,'edgealpha',0.2,'facealpha',0.15);hold on
xlim([ind_frames(1) ind_frames(end)]);