function realtime_frames(x,y,xlimt,color,edge,frame,trial,fs,startpoint)
% h=figure;
% x=times;%s
% y=showtrace(:,kk);y=y(frameinds);color=str2num(tracecolor(kk,2));
% xlimt=[frameind(1)*fs.ca frameind(end)*fs.ca];
linewidth=4;
%CS bar
CScolor=[1 1 1];edgealpha=1;facealpha=1;
if single(mod(x(end)/fs.ca,frame.per_cycle))==single(frame.cs_start)
    patch1=patch([[frame.cs_start+trial.spon_bef(3)*frame.per_cycle:frame.per_cycle:-mod(x(end)/fs.ca,frame.per_cycle)+length(x)+frame.per_cycle*(fix(xlimt(1)/fs.ca/frame.per_cycle))]'...
        [frame.cs_end+trial.spon_bef(3)*frame.per_cycle:frame.per_cycle:-mod(x(end)/fs.ca,frame.per_cycle)++length(x)+frame.per_cycle*(fix(xlimt(1)/fs.ca/frame.per_cycle))]'...
        [frame.cs_end+trial.spon_bef(3)*frame.per_cycle:frame.per_cycle:-mod(x(end)/fs.ca,frame.per_cycle)++length(x)+frame.per_cycle*(fix(xlimt(1)/fs.ca/frame.per_cycle))]'...
        [frame.cs_start+trial.spon_bef(3)*frame.per_cycle:frame.per_cycle:-mod(x(end)/fs.ca,frame.per_cycle)++length(x)+frame.per_cycle*(fix(xlimt(1)/fs.ca/frame.per_cycle))]']'*fs.ca,...
        repmat([edge(1) edge(1) edge(2) edge(2)],length([frame.cs_start+trial.spon_bef(3)*frame.per_cycle:frame.per_cycle:-mod(x(end)/fs.ca,frame.per_cycle)++length(x)+frame.per_cycle*(fix(xlimt(1)/fs.ca/frame.per_cycle))]),1)',...
        CScolor,'edgecolor',CScolor,'facecolor',CScolor,'edgealpha',edgealpha,'facealpha',facealpha);hold on
    line([x(end) x(end)],[edge(1),edge(2)],'color',CScolor);hold on;
elseif single(mod(x(end)/fs.ca,frame.per_cycle))>single(frame.cs_start) && single(mod(x(end)/fs.ca,frame.per_cycle))<single(frame.cs_end)
     patch1=patch([[frame.cs_start+trial.spon_bef(3)*frame.per_cycle:frame.per_cycle:-mod(x(end)/fs.ca,frame.per_cycle)+length(x)+frame.per_cycle*(fix(xlimt(1)/fs.ca/frame.per_cycle))]'...
        [frame.cs_end+trial.spon_bef(3)*frame.per_cycle:frame.per_cycle:-mod(x(end)/fs.ca,frame.per_cycle)++length(x)+frame.per_cycle*(fix(xlimt(1)/fs.ca/frame.per_cycle))]'...
        [frame.cs_end+trial.spon_bef(3)*frame.per_cycle:frame.per_cycle:-mod(x(end)/fs.ca,frame.per_cycle)++length(x)+frame.per_cycle*(fix(xlimt(1)/fs.ca/frame.per_cycle))]'...
        [frame.cs_start+trial.spon_bef(3)*frame.per_cycle:frame.per_cycle:-mod(x(end)/fs.ca,frame.per_cycle)++length(x)+frame.per_cycle*(fix(xlimt(1)/fs.ca/frame.per_cycle))]']'*fs.ca,...
        repmat([edge(1) edge(1) edge(2) edge(2)],length([frame.cs_start+trial.spon_bef(3)*frame.per_cycle:frame.per_cycle:-mod(x(end)/fs.ca,frame.per_cycle)++length(x)+frame.per_cycle*(fix(xlimt(1)/fs.ca/frame.per_cycle))]),1)',...
        CScolor,'edgecolor',CScolor,'facecolor',CScolor,'edgealpha',edgealpha,'facealpha',facealpha);hold on
    patch([(ceil(x(end)/fs.ca/frame.per_cycle)-1)*frame.per_cycle+frame.cs_start,...
        x(end)/fs.ca,...
        x(end)/fs.ca,...
        (ceil(x(end)/fs.ca/frame.per_cycle)-1)*frame.per_cycle+frame.cs_start]*fs.ca,...
        [edge(1) edge(1) edge(2) edge(2)],...
        CScolor,'edgecolor',CScolor,'facecolor',CScolor,'edgealpha',edgealpha,'facealpha',facealpha);hold on
else
patch1=patch([[frame.cs_start+trial.spon_bef(3)*frame.per_cycle:frame.per_cycle:length(x)+frame.per_cycle*(fix(xlimt(1)/fs.ca/frame.per_cycle))]'...
    [frame.cs_end+trial.spon_bef(3)*frame.per_cycle:frame.per_cycle:length(x)+frame.per_cycle*(fix(xlimt(1)/fs.ca/frame.per_cycle))]'...
    [frame.cs_end+trial.spon_bef(3)*frame.per_cycle:frame.per_cycle:length(x)+frame.per_cycle*(fix(xlimt(1)/fs.ca/frame.per_cycle))]'...
    [frame.cs_start+trial.spon_bef(3)*frame.per_cycle:frame.per_cycle:length(x)+frame.per_cycle*(fix(xlimt(1)/fs.ca/frame.per_cycle))]']'*fs.ca,...
    repmat([edge(1) edge(1) edge(2) edge(2)],length([frame.cs_start+trial.spon_bef(3)*frame.per_cycle:frame.per_cycle:length(x)+frame.per_cycle*(fix(xlimt(1)/fs.ca/frame.per_cycle))]),1)',...
    CScolor,'edgecolor',CScolor,'facecolor',CScolor,'edgealpha',edgealpha,'facealpha',facealpha);hold on
end
%US line
if ~isempty([(frame.us_start+trial.hab(3)*frame.per_cycle):frame.per_cycle:length(x)+frame.per_cycle*(fix(xlimt(1)/fs.ca/frame.per_cycle))])
    l3=line(([[(frame.us_start+trial.hab(3)*frame.per_cycle):frame.per_cycle:length(x)+frame.per_cycle*(fix(xlimt(1)/fs.ca/frame.per_cycle))];...
        [(frame.us_start+trial.hab(3)*frame.per_cycle):frame.per_cycle:length(x)+frame.per_cycle*(fix(xlimt(1)/fs.ca/frame.per_cycle))]])*fs.ca,...
        [edge(1) edge(2)],'color','r','LineStyle','--','linewidth',linewidth-0.5);hold on
end
%trace
plot(x,y,'color',color,'linewidth',linewidth);hold on;

xlim([xlimt(1) xlimt(2)]);ylim([edge(1),edge(2)]);

