function main_Caimg
%%%%%%%%%加T2适用于光遗传
clc;
clear all;

% % %导入参数文件，文件里的参数会被调入主面板各参数栏内。
% if exist('param.txt','file')==2
%      opt=readtxt2structure('param.txt');%如果存在param.txt，则导入到当前参数矩阵
%   else 
%      opt=readtxt2structure('defaultparam.txt');%如果不存在param.txt，则导入默认文件到当前参数矩阵
% end

%%%%%%%%%%%%%%%%%%%%%%%%%%BUILD GUI%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%bulid figure
hf=figure( 'units','pixels',...
           'position',[250 150 945 685],...
           'name','Ca imaging processing',...
           'menubar','none',...
           'numbertitle','off',...
           'color',[0.925 0.914 0.847],...
           'tag','hmainfigure');    
%建立panel框
hopt=uipanel('title','Opt-parameters',...%%%%L
           'titleposition','lefttop',...
           'units','pixels',...
           'position',[28 21 900 330],...
           'FontSize',10,...
           'tag','optpanel',...
           'foregroundcolor',[0 0.5 1]);
hdis=uipanel('title','Display',...%%%%L
           'titleposition','lefttop',...
           'units','pixels',...
           'position',[28 21+330+20 526 300],...
           'FontSize',10,...
           'tag','dispanel',...
           'foregroundcolor',[0 0.5 1]);
hdisedit=uicontrol( hdis,'style','edit','units','pixels', 'fontsize',10,'max',20,...
                     'position',[5 10 502 280],'horizontalalignment','left',...
                     'callback',@displayresult,...
                     'tag','dis_tag','backgroundcolor',[1 1 1]);
%建立结果展示并设置其显示范围

%%%%%%%%%%建立参数文本%%%%%%%%%%
%OPT-paramenters
% htextimagpath=uicontrol( hopt,...
%                      'style','text',...
%                      'units','pixels',...
%                      'fontsize',10,...
%                      'position',[12 219 75 24],...
%                      'string','imagpath');
% heditimagpath=uicontrol( hopt,...
%                      'style','edit',...
%                      'units','pixels',...
%                      'fontsize',10,...
%                      'position',[102 219 70 24],...
%                      'tag','Lxposition_tag','backgroundcolor',[1 1 1]);
%volume T/T2/t0
htextT=uicontrol( hopt, 'style','text','units','pixels', 'fontsize',10,...
                     'position',[2 280 80 24], 'string','T');
heditT=uicontrol( hopt,'style','edit','units','pixels', 'fontsize',10,...
                     'position',[2+80+10 280 70 24], 'string','25',...
                     'tag','T_tag','backgroundcolor',[1 1 1]);
htextt0=uicontrol( hopt,'style','text','units','pixels','fontsize',10,...
                     'position',[2+80+10+90 280 80 24],'string','t0');
heditt0=uicontrol( hopt, 'style','edit', 'units','pixels','fontsize',10,...
                     'position',[2+90*3 280 70 24],'tag','t0_tag','backgroundcolor',[1 1 1]);
%  htextT2=uicontrol( hopt,...
%                      'style','text', 'units','pixels','fontsize',10,...
%                      'position',[226 219 75 24],'string','T2');
% heditT2=uicontrol( hopt,...
%                      'style','edit','units','pixels','fontsize',10,...
%                      'position',[312 219 70 24],...
%                      'string','24',...'tag','T2_tag','backgroundcolor',[1 1 1]);
htextpoolsize=uicontrol( hopt,'style','text','units','pixels','fontsize',10,...
                     'position',[2+90*4 280 80 24],'string','Poolsize');
heditpoolsize=uicontrol( hopt, 'style','edit', 'units','pixels','fontsize',10,...
                     'position',[2+90*5 280 70 24], 'string','12','tag','poolsize_tag','backgroundcolor',[1 1 1]);
%核定位，是否配准，提信号
htextnuc=uicontrol( hopt,...
                     'style','text','units','pixels','fontsize',10,...
                     'position',[2 280-30 80 24],...
                     'string','Loc_nucleus');
heditnuc=uicontrol( hopt,'style','popup','units','pixels', 'fontsize',10,...
                     'position',[2+80+10 280-34 70 24],'string','True|False',...
                     'tag','loc_nucleus_tag','backgroundcolor',[1 1 1]);     
htextisres=uicontrol( hopt,...
                     'style','text','units','pixels','fontsize',10,...
                     'position',[2+90*2 280-34 80 24],...
                     'string','Isregistration');
heditisres=uicontrol( hopt,'style','popup','units','pixels', 'fontsize',10,...
                     'position',[2+90*3 280-34 70 24],'string','True|False',...
                     'tag','isregistration_tag','backgroundcolor',[1 1 1]);  
htextextracts=uicontrol( hopt,...
                     'style','text','units','pixels','fontsize',10,...
                     'position',[2+90*4 280-34 80 24],...
                     'string','Extract signal multicore');
heditextracts=uicontrol( hopt,'style','popup','units','pixels', 'fontsize',10,...
                     'position',[2+90*5 280-34 70 24],'string','True|False',...
                     'tag','extractsignal_tag','backgroundcolor',[1 1 1]);                                     
%average mask参数
htextnsample=uicontrol( hopt, 'style','text','units','pixels', 'fontsize',10,...
                     'position',[2 280-34-34 80 24], 'string','nsample');
heditnsample=uicontrol( hopt,'style','edit','units','pixels', 'fontsize',10,...
                     'position',[2+80+10 280-34-34 70 24], 'string','128',...
                     'tag','nsample_tag','backgroundcolor',[1 1 1]);
htextzi=uicontrol( hopt, 'style','text','units','pixels', 'fontsize',10,...
                     'position',[2+90*2 280-34-34 75 24], 'string','Z');
heditzi=uicontrol( hopt,'style','edit','units','pixels', 'fontsize',10,...
                     'position',[2+90*3 280-34-34 70 24], 'string','17',...
                     'tag','zi_tag','backgroundcolor',[1 1 1]);
%分割参数
htextminrad=uicontrol( hopt, 'style','text','units','pixels', 'fontsize',10,...
                     'position',[2 280-34*3 80 24], 'string','Minrad');
heditminrad=uicontrol( hopt,'style','edit','units','pixels', 'fontsize',10,...
                     'position',[2+80+10 280-34*3 70 24], 'string','3',...
                     'tag','minrad_tag','backgroundcolor',[1 1 1]);
htextmaxrad=uicontrol( hopt, 'style','text','units','pixels', 'fontsize',10,...
                     'position',[2+90*2 280-34*3 80 24], 'string','Maxrad');
heditmaxrad=uicontrol( hopt,'style','edit','units','pixels', 'fontsize',10,...
                     'position',[2+90*3 280-34*3 70 24], 'string','7',...
                     'tag','maxrad_tag','backgroundcolor',[1 1 1]);                 
htextthres=uicontrol( hopt, 'style','text','units','pixels', 'fontsize',10,...
                     'position',[2+90*4 280-34*3 80 24], 'string','Thres');
heditthres=uicontrol( hopt,'style','edit','units','pixels', 'fontsize',10,...
                     'position',[2+90*5 280-34*3 70 24],...
                     'tag','thres_tag','backgroundcolor',[1 1 1]);  
%配准参数
htextdensity=uicontrol( hopt, 'style','text','units','pixels', 'fontsize',10,...
                     'position',[2 280-34*4 80 24], 'string','Density');
heditdensity=uicontrol( hopt,'style','edit','units','pixels', 'fontsize',10,...
                     'position',[2+80+10 280-34*4 70 24], 'string','80',...
                     'tag','density_tag','backgroundcolor',[1 1 1]);  
htextsquaresize=uicontrol( hopt, 'style','text','units','pixels', 'fontsize',10,...
                     'position',[2+90*2 280-34*4 75 24], 'string','Squaresize');
heditsquaresize=uicontrol( hopt,'style','edit','units','pixels', 'fontsize',10,...
                     'position',[2+90*3 280-34*4 70 24], 'string','128',...
                     'tag','squaresize_tag','backgroundcolor',[1 1 1]); 
htextshift=uicontrol( hopt, 'style','text','units','pixels', 'fontsize',10,...
                     'position',[2+90*4 280-34*4 75 24], 'string','Shift');
heditshift=uicontrol( hopt,'style','edit','units','pixels', 'fontsize',10,...
                     'position',[2+90*5 280-34*4 70 24], 'string','12',...
                     'tag','shift_tag','backgroundcolor',[1 1 1]); 
%%%%%%%%%%建立控制按钮%%%%%%%%%%
%建立run按钮
hrun=uicontrol( gcf,...
                'style','pushbutton','backgroundcolor',[0 1 0],'fontweight','bold','fontsize',10,'units','pixels',...
                'position',[28+526+20 21+330+20+250 120 40],...
                'string','RUN',...
                'callback',@(x,y)callback_run,...
                'tag','run_push');             
%建立pause按钮（控制时间）
hpause=uicontrol( gcf,...
                  'style','pushbutton', 'backgroundcolor',[0.5 0.5 1],'fontweight','bold','fontsize',10,'units','pixels',...
                  'position',[28+526+20 21+330+20+190 120 40],...
                  'string','PAUSE',...'callback',{@pausetest,1}, ...
                  'tag','pause_push',...
                  'enable','off');
%建立stop按钮
hstop=uicontrol( gcf,...
                 'style','pushbutton', 'backgroundcolor',[1 0 0], 'fontweight','bold', 'fontsize',10,'units','pixels',...
                 'position',[28+526+20 21+330+20+130 120 40],...
                 'string','STOP',... 
                 'callback',@(x,y)callback_stop,...
                 'tag','stop_push');
%建立exit按钮
hexit=uicontrol( gcf,... 
                 'style','pushbutton', 'backgroundcolor',[0.5 0.5 0.5],'fontweight','bold','fontsize',10,... 
                 'units','pixels',...
                 'position',[28+526+20+140 21+330+20+250 120 40],...
                 'string','Exit', ...
                 'callback',@(x,y)callback_exit,...
                'tag','exit_push');
%建立readme按钮
hexit=uicontrol( gcf,... 
                 'style','pushbutton','backgroundcolor',[0.5 0.5 0.5], 'fontweight','bold', 'fontsize',10,'units','pixels',...
                 'position',[28+526+20+140 21+330+20+190 120 40],...
                 'string','Readme',...
                 'callback',@(x,y)callback_readme,...
                'tag','readme_push');
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
end